FROM debian:bookworm-slim AS aws-lc-builder

ENV AWSLC_URL=https://github.com/aws/aws-lc.git
ENV AWSLC_TAG=v1.66.1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        git \
        cmake \
        ninja-build \
        golang \
    && \
    git clone --depth 1 --branch "${AWSLC_TAG}" "${AWSLC_URL}" /tmp/aws-lc && \
    mkdir /tmp/aws-lc/build && \
    cd /tmp/aws-lc/build && \
    cmake -G Ninja \
          -DCMAKE_INSTALL_PREFIX=/opt/aws-lc \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=ON \
          .. && \
    ninja install && \
    rm -rf /tmp/aws-lc

FROM debian:bookworm-slim AS haproxy-builder

# see: https://git.haproxy.org/git/haproxy-3.2.git/refs/tags/
ENV HAPROXY_BRANCH=3.2
ENV HAPROXY_MINOR=3.2.9
ENV HAPROXY_SHA256=e660d141b29019f4d198785b0834cc3e9c96efceeb807c2fff2fc935bd3354c2
ENV HAPROXY_SRC_URL=https://www.haproxy.org/download
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=aws-lc-builder /opt/aws-lc /opt/aws-lc

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps zlib1g "libpcre2-*" liblua5.4-0 libatomic1 tar curl socat ca-certificates && \
    apt-get install -y --no-install-recommends gcc make libc6-dev libpcre2-dev zlib1g-dev liblua5.4-dev && \
    curl -sfSL "${HAPROXY_SRC_URL}/${HAPROXY_BRANCH}/src/haproxy-${HAPROXY_MINOR}.tar.gz" -o haproxy.tar.gz && \
    echo "$HAPROXY_SHA256 *haproxy.tar.gz" | sha256sum -c - && \
    mkdir -p /tmp/haproxy && \
    tar -xzf haproxy.tar.gz -C /tmp/haproxy --strip-components=1 && \
    rm -f haproxy.tar.gz

RUN make -C /tmp/haproxy -j"$(nproc)" TARGET=linux-glibc CPU=generic USE_PCRE2=1 USE_PCRE2_JIT=1 \
                          USE_TFO=1 USE_LINUX_TPROXY=1 USE_LUA=1 USE_GETADDRINFO=1 \
                          USE_PROMEX=1 USE_SLZ=1 \
                          USE_OPENSSL_AWSLC=1 USE_PTHREAD_EMULATION=1 \
                          SSL_INC=/opt/aws-lc/include SSL_LIB=/opt/aws-lc/lib USE_QUIC=1 \
                          LDFLAGS="-L/opt/aws-lc/lib -Wl,-rpath,/opt/aws-lc/lib" \
                          all

RUN make -C /tmp/haproxy TARGET=linux-glibc install-bin

FROM debian:bookworm-slim

LABEL Name="HAProxy"
LABEL Release="Community Edition"
LABEL Vendor=HAProxy
LABEL Version=3.2.9
LABEL Maintainer="Pascal Rath <contact+haproxy@oxl.at>"

ENV HAPROXY_UID=haproxy
ENV HAPROXY_GID=haproxy
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=aws-lc-builder /opt/aws-lc /opt/aws-lc
COPY --from=haproxy-builder /usr/local/sbin/haproxy /usr/local/sbin/haproxy
COPY --from=haproxy-builder /tmp/haproxy/examples/errorfiles/ /etc/haproxy/errors

RUN apt-get update && \
    apt-get install -y --no-install-recommends procps zlib1g "libpcre2-*" liblua5.4-0 libatomic1 tar curl socat ca-certificates && \
    groupadd "$HAPROXY_GID" && \
    useradd -g "$HAPROXY_GID" "$HAPROXY_UID" && \
    ln -s /usr/local/sbin/haproxy /usr/sbin/haproxy && \
    mkdir -p /var/lib/haproxy && \
    chown "$HAPROXY_UID:$HAPROXY_GID" /var/lib/haproxy && \
    mkdir -p /etc/haproxy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "/opt/aws-lc/lib" > /etc/ld.so.conf.d/awslc.conf && \
    mkdir -p /opt/aws-lc/ssl && \
    rm -rf /opt/aws-lc/ssl/certs && \
    ln -s /etc/ssl/certs /opt/aws-lc/ssl/certs && \
    ldconfig

COPY --chmod=755 docker-entrypoint.sh /

STOPSIGNAL SIGUSR1

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["haproxy", "-W", "-f", "/etc/haproxy/haproxy.cfg"]